#!/usr/bin/env bash
#=====================================================================
#  CQT – Production‑ready validation harness
#
#  Location:   scripts/validate.sh
#  Called by:  go_live.sh   (after the engine containers have been
#                           pulled & started on BOTH engine droplets)
#
#  What it does
#  -------------
#  1️⃣  Checks private‑IP reachability between all droplets.
#  2️⃣  Verifies the DigitalOcean Load‑Balancer DNS and TLS health‑check.
#  3️⃣  Confirms Docker‑Compose reports healthy containers on primary &
#      standby.
#  4️⃣  Makes sure Prometheus sees both engines as UP.
#  5️⃣  Tests the Grafana datasource (Prometheus) and the Mission‑Control
#      Text‑panel weight‑update round‑trip.
#  6️⃣  Executes a full paper‑trade flow and validates the DB row.
#  7️⃣  Enforces the max‑open‑positions limit.
#  8️⃣  Triggers a simulated draw‑down → verifies the kill‑switch.
#  9️⃣  Performs a Load‑Balancer fail‑over test (stop primary, query API).
#  🔟  Fires a manual backup‑svc run and checks that a recent snapshot
#      exists.
#  1️⃣1️⃣ Security sanity checks (API token required, SSH firewall).
#  1️⃣2️⃣ Alerting sanity check (high‑risk alert fires).
#  1️⃣3️⃣ Performance baseline (CPU usage, Prometheus scrape latency).
#  1️⃣4️⃣ Writes a concise JSON summary for CI / audit logs.
#
#  Exit status: 0 = all checks passed, 1 = any failure.
#=====================================================================

set -euo pipefail

#---------------------------------------------------------------------
#  Load environment variables (generated by go_live.sh)
#---------------------------------------------------------------------
# The file must export at least the following vars:
#   LB_IP          – public IP of the Managed Load Balancer
#   API_TOKEN      – bearer token for the Flask API
#   GF_TOKEN       – Grafana API token (admin)
#   PRIMARY_IP     – private IP of the primary engine droplet
#   STANDBY_IP     – private IP of the standby engine droplet
#   DB_IP          – private IP of the PostgreSQL droplet
#   MONITOR_IP     – private IP of the Prometheus droplet
#   GRAFANA_IP     – private IP of the Grafana droplet
#   BACKUP_IP      – private IP of the backup‑svc droplet
#   LB_ID          – DigitalOcean Load‑Balancer ID (used for health‑check)
#   VPC_CIDR       – e.g. 10.10.0.0/16
#   ADMIN_IP       – your own public IP (used for SSH firewall test)
#
# If the file does not exist the script aborts.
#---------------------------------------------------------------------
if [[ -f "./cqt_env.sh" ]]; then
    source "./cqt_env.sh"
else
    # ✅ FIXED: Redirect error message to stderr (>&2)
    echo "❌ ERROR – cqt_env.sh not found. Abort." >&2
    exit 1
fi

#---------------------------------------------------------------------
#  Helper functions
#  ✅ FIXED: Added explicit return statements to all functions
#---------------------------------------------------------------------
log() {
    echo -e "\e[32m[+] $*\e[0m"
    return 0
}

warn() {
    echo -e "\e[33m[!] $*\e[0m"
    return 0
}

error() {
    echo -e "\e[31m[✖] $*\e[0m" >&2
    return 1
}

die() {
    error "$*"
    exit 1
    # Explicit return for SonarCloud S1871 (unreachable but required)
    return 1
}

# Simple wrapper for curl that fails on non‑2xx codes
curl_ok() {
    local url=$1
    local hdrs=$2
    curl -sSf $hdrs "$url" >/dev/null
    return $?
}

#---------------------------------------------------------------------
#  ✅ FIXED: Added explicit return statement to check_compose_health
#---------------------------------------------------------------------
check_compose_health() {
    local host=$1
    ssh root@"$host" \
        "docker compose ps --format '{{.Service}} {{.State}} {{.Health}}'" |
        awk '/engine/ {if ($2!="running" || $3!="healthy") exit 1}'
    return $?
}

#---------------------------------------------------------------------
#  1️⃣  Network sanity – private‑IP reachability
#---------------------------------------------------------------------
log "🔎 Verifying private‑IP reachability (SSH on port 22)"
for name in primary standby db monitor grafana backup; do
    ip_var="${name^^}_IP"
    ip="${!ip_var}"
    [[ -z "$ip" ]] && die "Variable $ip_var not set"
    if nc -zvw2 "$ip" 22 >/dev/null 2>&1; then
        log "$name ($ip) – SSH reachable"
    else
        die "Cannot reach $name ($ip) on port 22"
    fi
done

#---------------------------------------------------------------------
#  2️⃣  Load‑Balancer DNS & health‑check
#---------------------------------------------------------------------
log "🔎 Resolving Load‑Balancer DNS"
resolved_ip=$(dig +short api.cqt.example.com | head -n1)
if [[ "$resolved_ip" != "$LB_IP" ]]; then
    die "LB DNS resolves to $resolved_ip, expected $LB_IP"
fi
log "✅ LB DNS resolves correctly → $resolved_ip"

log "🔎 Testing LB health endpoint (HTTPS, bearer token)"
if ! curl_ok "https://api.cqt.example.com/healthz" \
            "-H \"Authorization: Bearer $API_TOKEN\" --max-time 5"; then
    die "LB health check failed"
fi
log "✅ LB health endpoint OK (200)"

#---------------------------------------------------------------------
#  3️⃣  Docker‑Compose health on primary & standby
#---------------------------------------------------------------------
log "🔎 Verifying Docker‑Compose health on primary"
if ! check_compose_health "$PRIMARY_IP"; then
    die "Primary engine unhealthy"
fi
log "✅ Primary engine healthy"

log "🔎 Verifying Docker‑Compose health on standby"
if ! check_compose_health "$STANDBY_IP"; then
    die "Standby engine unhealthy"
fi
log "✅ Standby engine healthy"

#---------------------------------------------------------------------
#  4️⃣  Prometheus targets
#---------------------------------------------------------------------
log "🔎 Fetching Prometheus target status"
targets=$(curl -s "http://$MONITOR_IP:9090/api/v1/targets")
echo "$targets" | jq -r '.data.activeTargets[] |
    "\(.labels.job) \(.health)"' |
while read -r job health; do
    if [[ "$health" != "up" ]]; then
        die "Prometheus target $job is $health"
    fi
done
log "✅ All Prometheus targets are up"

#---------------------------------------------------------------------
#  5️⃣  Grafana datasource sanity
#---------------------------------------------------------------------
log "🔎 Checking Grafana datasource (expects Prometheus URL)"
ds=$(curl -s -H "Authorization: Bearer $GF_TOKEN" \
        "http://$GRAFANA_IP:3000/api/datasources")
echo "$ds" | jq -r '.[] |
    select(.type=="prometheus") |
    .url' |
grep -q "$MONITOR_IP:9090" || die "Grafana datasource not pointing to Prometheus"
log "✅ Grafana datasource OK"

#---------------------------------------------------------------------
#  6️⃣  Mission‑Control UI – weight round‑trip
#---------------------------------------------------------------------
log "🔎 Testing weight update via Mission‑Control"
new_weight=$(awk -v min=0.20 -v max=0.30 'BEGIN{srand(); printf "%.2f", min+rand()*(max-min)}')
curl -s -X POST "https://api.cqt.example.com/config/weight_mtf_structure" \
     -H "Authorization: Bearer $API_TOKEN" \
     -H "Content-Type: application/json" \
     -d "{\"value\":$new_weight}" >/dev/null

# Verify Prometheus gauge reflects the change
gauge=$(curl -s "http://$MONITOR_IP:9090/api/v1/query?query=confluence_parameter{parameter=\"weight_mtf_structure\"}" |
        jq -r '.data.result[0].value[1]')
if [[ "$gauge" != "$new_weight" ]]; then
    die "Gauge mismatch – expected $new_weight, got $gauge"
fi
log "✅ Weight update round‑trip succeeded (value=$new_weight)"

#---------------------------------------------------------------------
#  7️⃣  Paper‑trade end‑to‑end flow
#---------------------------------------------------------------------
log "🔎 Submitting a paper‑trade simulation"
sim_resp=$(curl -s -X POST "https://api.cqt.example.com/simulate" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"symbol":"EURUSD","direction":"BUY","entry_price":1.0800}')
trade_id=$(echo "$sim_resp" | jq -r '.trade_id // empty')
[[ -n "$trade_id" ]] || die "Simulation response missing trade_id"
log "✅ Simulation submitted, trade_id=$trade_id"

log "🔎 Verifying trade persisted in TimescaleDB"
db_check=$(ssh root@"$DB_IP" \
    "docker exec timescaledb psql -U cqt_user -d cqt_ledger -t -c \"SELECT trade_id FROM trades WHERE trade_id=$trade_id;\"")
if [[ "$db_check" != "$trade_id" ]]; then
    die "Trade $trade_id not found in DB"
fi
log "✅ Trade $trade_id successfully stored"

#---------------------------------------------------------------------
#  8️⃣  Position‑limit enforcement (max 4 open positions)
#---------------------------------------------------------------------
log "🔎 Testing max‑open‑positions limit (configured = 4)"
for i in {1..4}; do
    curl -s -X POST "https://api.cqt.example.com/simulate" \
        -H "Authorization: Bearer $API_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"symbol":"GBPUSD","direction":"BUY","entry_price":1.2600}' >/dev/null
done
# Fifth trade should be rejected
reject=$(curl -s -X POST "https://api.cqt.example.com/simulate" \
    -H "Authorization: Bearer $API_TOKEN" \
    -H "Content-Type: application/json" \
    -d '{"symbol":"USDJPY","direction":"BUY","entry_price":138.00}')
echo "$reject" | jq -e '.should_trade==false' >/dev/null ||
    die "Position limit not enforced"
log "✅ Position‑limit correctly enforced"

#---------------------------------------------------------------------
#  9️⃣  Kill‑switch (draw‑down) test
#---------------------------------------------------------------------
log "🔎 Forcing a >3 % daily draw‑down to trigger kill‑switch"
ssh root@"$DB_IP" \
    "docker exec timescaledb psql -U cqt_user -d cqt_ledger -c \"UPDATE ledger_meta SET equity = equity * 0.94 WHERE id=1;\""
# Give the engine a few seconds to react
sleep 12
ks_status=$(curl -s "https://api.cqt.example.com/killswitch" \
    -H "Authorization: Bearer $API_TOKEN")
echo "$ks_status" | jq -e '.active==true' >/dev/null ||
    die "Kill‑switch did not activate"
log "✅ Kill‑switch activated as expected"

#---------------------------------------------------------------------
#  🔟  Load‑Balancer fail‑over test
#---------------------------------------------------------------------
log "🔎 Testing automatic fail‑over (stopping primary engine)"
ssh root@"$PRIMARY_IP" "docker compose stop engine"
# API should still respond via standby
curl -s -f "https://api.cqt.example.com/config" \
    -H "Authorization: Bearer $API_TOKEN" |
    jq . >/dev/null || die "API unreachable after primary stopped"
log "✅ Fail‑over succeeded – standby serving traffic"

log "🔎 Restoring primary engine"
ssh root@"$PRIMARY_IP" "docker compose start engine"
sleep 5
lb_status=$(doctl compute load-balancer get "$LB_ID" --output json |
            jq -r '.droplet_ids | length')
if [[ "$lb_status" -ne 2 ]]; then
    die "Load‑balancer does not report two healthy droplets"
fi
log "✅ Primary engine restored; both back‑ends healthy"

#---------------------------------------------------------------------
#  1️⃣1️⃣  Backup‑svc snapshot sanity check
#---------------------------------------------------------------------
log "🔎 Triggering manual backup (snapshot + log archive)"
ssh root@"$BACKUP_IP" "/usr/local/bin/cqt_backup.sh"
snap=$(doctl compute snapshot list --resource-type volume --output json |
       jq -r '.[] | select(.name|contains("cqt-pg-data")) | .created_at' |
       head -n1)
[[ -n "$snap" ]] || die "No recent DB volume snapshot found"
log "✅ Backup snapshot created at $snap"

#---------------------------------------------------------------------
#  1️⃣2️⃣  Security sanity checks
#---------------------------------------------------------------------
log "🔎 Ensuring API rejects unauthenticated requests"
unauth_code=$(curl -s -o /dev/null -w "%{http_code}" \
    "https://api.cqt.example.com/config")
if [[ "$unauth_code" -ne 401 ]]; then
    die "Unauthenticated request returned $unauth_code (expected 401)"
fi
log "✅ API correctly requires bearer token"

log "🔎 Verifying SSH firewall (only admin IP allowed)"
# Try SSH from a throw‑away container that is *not* in ADMIN_IP CIDR
temp_ip=$(docker run --rm alpine:latest ip -4 addr show eth0 |
          awk '/inet/ {print $2}' | cut -d/ -f1)
ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 \
    root@"$PRIMARY_IP" exit >/dev/null 2>&1 &&
    die "SSH succeeded from unauthorized IP $temp_ip" ||
    log "✅ SSH correctly blocked from $temp_ip"

#---------------------------------------------------------------------
#  1️⃣3️⃣  Alerting sanity check (high risk fraction)
#---------------------------------------------------------------------
log "🔎 Temporarily forcing high risk fraction to fire alert"
curl -s -X POST "https://api.cqt.example.com/config/min_total_score" \
     -H "Authorization: Bearer $API_TOKEN" \
     -H "Content-Type: application/json" \
     -d '{"value":10}' >/dev/null
# Give Alertmanager a moment to propagate
sleep 8
alert_state=$(curl -s -H "Authorization: Bearer $GF_TOKEN" \
    "http://$GRAFANA_IP:3000/api/alert-notifications" |
    jq -r '.[] | select(.state=="alerting") | .name' |
    grep -i "HighDynamicRisk" || true)
if [[ -n "$alert_state" ]]; then
    log "✅ Alert triggered (HighDynamicRisk)"
else
    warn "⚠️ Alert did not fire – check Alertmanager configuration"
fi

#---------------------------------------------------------------------
#  1️⃣4️⃣  Performance baseline (CPU & scrape latency)
#---------------------------------------------------------------------
log "🔎 Collecting CPU usage snapshot on primary"
cpu_usage=$(ssh root@"$PRIMARY_IP" \
    "docker stats --no-stream --format '{{.CPUPerc}}' engine")
log "✅ Primary engine CPU usage: $cpu_usage"

log "🔎 Checking Prometheus scrape duration for engine targets"
scrape_ms=$(curl -s "http://$MONITOR_IP:9090/api/v1/query?query=prometheus_target_scrape_duration_seconds" |
            jq -r '.data.result[] |
                select(.metric.job=="cqt_engine") |
                .value[1]' |
            awk '{printf "%.0f", $1*1000}')
log "✅ Average scrape duration for cqt_engine: ${scrape_ms} ms"

#---------------------------------------------------------------------
#  1️⃣5️⃣  Write a concise JSON summary (CI / audit friendly)
#---------------------------------------------------------------------
log "🔎 Generating validation‑run summary"
summary_file="/var/log/cqt_validation_summary.json"
cat > "$summary_file" <<EOF
{
  "timestamp": "$(date --utc +'%Y-%m-%dT%H:%M:%SZ')",
  "network": {
    "lb_dns_resolves_to": "$resolved_ip",
    "ssh_reachable": true
  },
  "services": {
    "primary_engine_healthy": true,
    "standby_engine_healthy": true,
    "prometheus_targets_up": true,
    "grafana_datasource_ok": true
  },
  "functional": {
    "weight_update_successful": true,
    "paper_trade_stored": true,
    "position_limit_enforced": true,
    "kill_switch_triggered": true,
    "failover_successful": true
  },
  "security": {
    "api_requires_token": true,
    "ssh_firewall_enforced": true
  },
  "alerts": {
    "high_dynamic_risk_fired": $( [[ -n "$alert_state" ]] && echo "true" || echo "false" )
  },
  "performance": {
    "engine_cpu_percent": "$cpu_usage",
    "prometheus_scrape_ms": $scrape_ms
  },
  "backup": {
    "snapshot_created": true,
    "snapshot_timestamp": "$snap"
  }
}
EOF
log "✅ Validation summary written to $summary_file"

exit 0
